services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:8.6.4
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend/libtrack-ui
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: