spring.application.name=LibTrack

spring.datasource.url=jdbc:postgresql://localhost:5433/LibTrackDB
spring.datasource.username=user
spring.datasource.password=secretDB
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.analytics-enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

jwt.secret=MySuperSecretKeyThatIsLongEnoughForHS256Algorithm123456789123
jwt.expiration-ms=3600000